### ISSUE TITLE
Accessing network data tables

### ISSUE THREAD

**Issue by leath02** [UTFOIL/Vectorization-Public#4]
Hello, I was wondering if I could get some assistance with the output of this program?

I am trying to access that data used to plot the matlab histograms that are generated by the program, for example strand radius, inverse tortuosity, etc. How can I directly access this data used for these plots in tabular format? In order to plot it myself, and combine it with other vessel networks I am examining.

I am also trying to access the filtered output image as a .tif z-stack, in order to have a version of my input .tif stack without the noise. Is this already present in this program or will it require changes?

Thank you so much!

**Comment by mihelics** [comment]
Thank you for raising this issue, @leath02.

Yes, all of the intermediate and output data is available inside the output directory (which has the format `batch_YYMMDD-hhmmss`, e.g. `batch_231113_244800`).  Please see the section of [the documentation](https://github.com/UTFOIL/Vectorization-Public#documentation) on `Outputs` for more information. I will summarize the relevant parts to your issue here:

1. You will find the raw data used to generate the histograms inside the "vectors" folder in the file called `network_YYMMDD-hhmmss_*.mat`. Alternatively, you will find this information offered in other formats, e.g. `*.vmv` format. Please see the part of the [software overview in the read me](https://github.com/UTFOIL/Vectorization-Public#software-overview) that links to the documentation on these output formats. 
      - Specify `vmv` (default) or `casx` as the output format in the `SpecialOutput` name/value pair input to the main vectorization function, vectorize_V200. Please see the `Logistical Parameters` section of the [the documentation](https://github.com/UTFOIL/Vectorization-Public#documentation).

   - This file contains all of the data associated with the final `network` processing step of the software. 
   - Many statistics are automatically calculated on a strand-basis and saved in the network file under the variable named `network_statistics`.
   - You could calculate any statistic you want from one the final network output (collection of locations in three-dimensional space, their one-dimensional connections, and the diameters associated with each position or connection). 
 
2. You will find the (multi-scale, linearly) filtered image in the `visual_data` folder as `energy_*.tif` (and in the `data` folder as an h5 file). 

   - Please note that this is not an output but an intermediate. The vertex objects are extracted from this and then serve as seed points for connecting the network along traces. Please see the `Methods` section of [the documentation](https://github.com/UTFOIL/Vectorization-Public#documentation) or [the methodology manuscript](https://github.com/UTFOIL/Vectorization-Public#methodology-manuscript)
   - There is also another image encoding the scale that is assigned to each voxel location called `energy_*_indices.tif` (which is part of the h5 file as a second entry in the 4th dimension).

Regards,
Sam

**Comment by leath02** [comment]
Excellent, thank you!
